feat: お知らせページとブログページの作成
AIM-SC/next-website pull request #16
Opened 2024-10-22 07:48 UTC by AIM-NSorachi

## チェック
- [ x] 余計な差分は存在しないか？

## 実装内容
お知らせページとブログページの実装

## スクショ
<img width="1792" alt="スクリーンショット 2024-10-22 16 44 48" src="https://github.com/user-attachments/assets/4251951a-9237-4c77-8b10-3bb97131f251">
<img width="1792" alt="スクリーンショット 2024-10-22 16 45 26" src="https://github.com/user-attachments/assets/137b83dd-edb2-4e79-85da-36ef2f366c01">
<img width="1792" alt="スクリーンショット 2024-10-22 16 45 43" src="https://github.com/user-attachments/assets/79ef89f9-356f-441f-9320-6f98601b35ad">
<img width="1792" alt="スクリーンショット 2024-10-22 16 45 51" src="https://github.com/user-attachments/assets/d7d77d39-6da7-4a8b-ab1b-f9d3661e4f59">

## issue
close 

## 懸念点
窪山さん管轄の共通コンポーネントは仮置きのものを作っているので後ほど置き換えます。

2024-10-24 02:33 UTC, AIM-KAmi0 requested changes
同じ部分はコメントしてないところもあるけど、お願いします。

2024-10-24 02:33 UTC, AIM-KAmi0 commented on src/app/(pages)/blog/[postId]/page.tsx
> +        <div className="container mx-auto bg-white p-[8%] rounded-xl min-h-[60vh]">
カード部分をコンポーネント化してほしい

2024-10-24 02:33 UTC, AIM-KAmi0 commented on libs/microcms.ts
> +  await new Promise((resolve) => setTimeout(resolve, 3000));
このmicro cmsの見本の記述いらないかな。

2024-10-24 02:33 UTC, AIM-KAmi0 commented on libs/microcms.ts
> +  await new Promise((resolve) => setTimeout(resolve, 3000));
ここも同様にいらないかな。

2024-10-24 02:33 UTC, AIM-KAmi0 commented on src/app/(pages)/blog/page.tsx
> +                    <div className="flex flex-wrap gap-2 text-xs text-white h-6">
タグもコンポーネント化してほしい。

2024-10-24 02:33 UTC, AIM-KAmi0 commented on src/app/(pages)/info/[postId]/page.tsx
> +              {post.tags.length > 0 ? (
ここも同様にコンポーネント化しといて。

2024-10-24 02:33 UTC, AIM-KAmi0 commented on src/app/(pages)/info/page.tsx
> +                      {post.tags.length > 0 ? (
ここも同じくコンポーネント化。

2024-10-24 02:33 UTC, AIM-KAmi0 commented on src/app/(pages)/info/page.tsx
> +                    width={300}
ここのwidthを360にすれば、tailwindで上からスタイルいらないんじゃない？

2024-10-24 02:33 UTC, AIM-KAmi0 commented on libs/microcms.ts
> +export type Tag = {
ここら辺の方はsrcの直下に`typed`ディレクトリを作って、その下に`microcms.ts`を作ってそこに入れてほしい。

2024-10-24 02:33 UTC, AIM-KAmi0 commented on src/app/(pages)/info/page.tsx
> +          className="fixed writing-mode-vertical-rl text-xs font-semibold tracking-wide"
tailwindで縦書きにするときにこうやってやるんだ。

2024-10-24 02:33 UTC, AIM-KAmi0 commented on src/app/(pages)/info/page.tsx
> +            <p className="font-lineSeed">AIM COMMONS</p>
font-lineSeedなんてクラスあったっけ？
これってミス？ドキュメント求む！！

2024-10-24 02:33 UTC, AIM-KAmi0 commented on public/img/exp.png
ディレクトリ名`images`みたいに複数形にしてほしい。

2024-10-24 02:33 UTC, AIM-KAmi0 commented on src/app/(pages)/info/[postId]/page.tsx
> +  if (!post) {
SSGでビルドするとき、この記述多分いらないと思う。

2024-10-24 07:58 UTC, Sora339 commented on src/app/(pages)/info/page.tsx
> +            <p className="font-lineSeed">AIM COMMONS</p>
ミスです。消しました。

2024-10-24 08:18 UTC, Sora339 commented on src/app/(pages)/info/[postId]/page.tsx
> +  if (!post) {
idはfilterがあるのでいらないですね。
postは消すと型エラーが出るのですが何か方法ありますか？

2024-10-28 04:00 UTC, Sora339 commented on src/app/(pages)/info/page.tsx
> +                    width={300}
widthはそうですね。修正しました。
CSSのheightは入れないとtailwindで被せてcoverにしないと画像が元の比率で表示されちゃってスタイルが著しく崩れてしまうのでこうしています。
next/imageに指定するwidthとheightは画像を読み込む解像度だと思っていたのですが、そうだとするとなぜ元のアスペクト比が維持されるのかがわかりません。
公式ドキュメントを読むと、読み込み時にレイアウトシフトが起こらないように画像をおく領域を確保するためのwidthとheightであり、画像の解像度に影響はないかのような書き方をされていますが、そうだとすると著しく小さな値を設定したときに画像が荒くなる理由がわかりません。レイアウトシフトが起こるにしても画像の解像度に影響はないように思えます。

2024-11-05 07:47 UTC, AIM-NSorachi commented on libs/microcms.ts
> +  await new Promise((resolve) => setTimeout(resolve, 3000));
削除しました。

2024-11-05 07:48 UTC, AIM-NSorachi commented on src/app/(pages)/info/page.tsx
> +            <p className="font-lineSeed">AIM COMMONS</p>
ミスです。削除しました。

2024-11-06 01:24 UTC, AIM-NSorachi commented on src/app/(pages)/info/[postId]/page.tsx
> +  if (!post) {
idはfilterがあるのでいらないですね。
postは消すと型エラーが出るのですが何か方法ありますか？

2024-11-06 01:25 UTC, AIM-NSorachi commented on src/app/(pages)/info/page.tsx
> +                    width={300}
widthはそうですね。修正しました。
CSSのheightは入れないとtailwindで被せてcoverにしないと画像が元の比率で表示されちゃってスタイルが著しく崩れてしまうのでこうしています。
next/imageに指定するwidthとheightは画像を読み込む解像度だと思っていたのですが、そうだとするとなぜ元のアスペクト比が維持されるのかがわかりません。
公式ドキュメントを読むと、読み込み時にレイアウトシフトが起こらないように画像をおく領域を確保するためのwidthとheightであり、画像の解像度に影響はないかのような書き方をされていますが、そうだとすると著しく小さな値を設定したときに画像が荒くなる理由がわかりません。レイアウトシフトが起こるにしても画像の解像度に影響はないように思えます。

2024-11-07 02:36 UTC, AIM-KAmi0 requested changes
<img width="1512" alt="スクリーンショット 2024-11-07 11 34 58" src="https://github.com/user-attachments/assets/7a80ec95-80d5-47d4-9f1e-0275e8983a03">

`https://localhost:3000/info/100`とかすると記事が存在しないのにページネーションが出てくる。これなんとかしてほしい。

2024-11-07 02:37 UTC, AIM-KAmi0 commented
あと、修正終わったら、resolve conservationを押しておいてほしい。

2024-11-07 03:20 UTC, AIM-KAmi0 approved these changes
LGTM

2024-11-07 06:36 UTC, merged