Feat/aim s kanoka/create toppage
AIM-SC/next-website pull request #20
Opened 2024-11-12 03:54 UTC by AIM-Skanoka

## チェック
- [ ] ページの作り方はこんな形で正しいのか

## 実装内容
トップページを作成しました。
一旦の状況で、こんな感じの作り方で良いのかを見ていただきたいです。
本来お知らせ部分はデータを引っ張ってきますが、一旦ダミーデータです。

## スクショ
![localhost_3000_top](https://github.com/user-attachments/assets/b7bf94ee-dbaf-448d-a611-506ddb5fd130)

## issue
close 

## 懸念点

2024-11-13 02:35 UTC, AIM-KAmi0 requested changes
```ts
import React from 'react';
```
は不要なので削除してもらって大丈夫です。

2024-11-13 02:35 UTC, AIM-KAmi0 commented on src/app/(pages)/top/page.tsx
> +"use client";
page.tsxは基本server componentsで、client componentsの部分だけ、コンポーネントで切り出して、クライアントにして欲しい。

2024-11-13 02:35 UTC, AIM-KAmi0 commented on src/app/(pages)/top/page.tsx
> +      <StyledSwiper
ここをコンポーネントに切り出して、"use client"にして欲しい。

2024-11-13 02:35 UTC, AIM-KAmi0 commented on src/app/components/title.tsx
> +interface titleProps {
オブジェクトの型は型エイリアスで定義してほしい。
Porps名も`Props`で統一していいかも。

```ts
type Props = {
   maintitle: string;
   subtitle: string;
}
````

あと、ジェネリクスで型を渡すのではなく、下記の書き方でお願いします。
```ts
const Title = ({  maintitle, subtitle }: Props) => {}
```

他のコンポーネントでもお願いします🙇

2024-11-14 03:11 UTC, AIM-KAmi0 commented on src/app/components/swiper.tsx
> +      <img src="\images\main01.jpg" alt="Slide 1" style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
ここnext/image使って欲しいです。

```ts
import { Image } from "next/image"
```

2024-11-14 03:12 UTC, AIM-KAmi0 commented on src/app/components/topCard.tsx
> +          <div key={item.name}> {}
この波かっこいらないかもです。

2024-11-21 02:17 UTC, AIM-Skanoka commented
![Uploading localhost_3000_top (1).png…]()

2024-11-21 02:19 UTC, AIM-Skanoka commented
![localhost_3000_top (2)](https://github.com/user-attachments/assets/4d99c76a-f598-4045-93df-9e2241021f74)

2024-11-21 02:54 UTC, AIM-KAmi0 approved these changes
[![LGTMeow](https://lgtm-images.lgtmeow.com/2024/10/25/10/6ad41699-a256-4f46-ba6d-8dfd0015e925.webp)](https://lgtmeow.com)

2024-11-21 02:55 UTC, merged